Repository nagaokakid/brainstorm, pull requests merged in 2023-12, with the labels that each got.

#287 change to dotnet 7
  Backend/Database.UnitTest/Database.UnitTest.csproj
  Backend/Database/Database.csproj
  Backend/Logic.IntegrationTest/Logic.IntegrationTest.csproj
  Backend/Logic.UnitTest/Hubs/ChatRoomHubTests.cs
  Backend/Logic.UnitTest/Logic.UnitTest.csproj
  Backend/Logic/Logic.csproj
Labels: bug

#291 Added JMeter Websocket Extensions
  LoadTesting/apache-jmeter-5.6.2/backups/Load_balance_workflow-000001.jmx
  LoadTesting/apache-jmeter-5.6.2/backups/Load_balance_workflow-000002.jmx
  LoadTesting/apache-jmeter-5.6.2/backups/Load_balance_workflow-000003.jmx
  LoadTesting/apache-jmeter-5.6.2/backups/Load_balance_workflow-000004.jmx
  LoadTesting/apache-jmeter-5.6.2/bin/jmeter.log
  LoadTesting/apache-jmeter-5.6.2/lib/ext/JMeterWebSocketSampler-1.0.2-SNAPSHOT.jar
  LoadTesting/apache-jmeter-5.6.2/lib/ext/jmeter-plugins-manager-1.10.jar
  LoadTesting/apache-jmeter-5.6.2/lib/ext/jmeter-websocket-samplers-1.2.9.jar
Labels: feature

#294 Comments
  Backend/Database/CollectionContracts/IDirectMessageCollection.cs
  Backend/Database/CollectionContracts/IUserCollection.cs
  Backend/Database/Collections/BrainstormResultCollection.cs
  Backend/Database/Collections/ChatRoomCollection.cs
  Backend/Database/Collections/UserCollection.cs
  Backend/Database/Data/BrainstormResult.cs
  Backend/Database/Data/ChatRoom.cs
  Backend/Database/Data/ChatRoomMessage.cs
  Backend/Database/Data/DirectMessage.cs
  Backend/Database/Data/DirectMessageHistory.cs
  Backend/Database/MongoDB/MongoRepository.cs
  FrontEnd/src/components/BS_LocalIdeaList.tsx
  FrontEnd/src/components/BS_MemberList.tsx
  FrontEnd/src/components/ChatList.tsx
  FrontEnd/src/components/ChatRoomWindow.tsx
  FrontEnd/src/components/CreateBrainStormCustomize.tsx
  FrontEnd/src/components/CreateRoomCustomize.tsx
  FrontEnd/src/components/GuestJoin.tsx
  FrontEnd/src/components/HeaderNavBar.tsx
  FrontEnd/src/components/InputSendPrompt.tsx
  FrontEnd/src/components/MemberList.tsx
  FrontEnd/src/components/MessageBox.tsx
  FrontEnd/src/components/MessageInput.tsx
  FrontEnd/src/components/MessageWindow.tsx
  FrontEnd/src/components/NavigationBar.tsx
  FrontEnd/src/components/YesNoPrompt.tsx
  FrontEnd/src/components/handleIconHover.tsx
  FrontEnd/src/components/voting/VoteIdea.tsx
  FrontEnd/src/components/voting/VoteResult.tsx
  FrontEnd/src/components/voting/VoteResults.tsx
  FrontEnd/src/contexts/DataContext.tsx
  FrontEnd/src/models/Idea.ts
  FrontEnd/src/models/TypesDefine.ts
  FrontEnd/src/pages/BrainStormPage.tsx
  FrontEnd/src/pages/LoginPage.tsx
  FrontEnd/src/pages/MainPage.tsx
  FrontEnd/src/services/ApiService.ts
  FrontEnd/src/services/ChatRoomConnection.ts
  FrontEnd/src/services/UserInfo.ts
  FrontEnd/src/styles/BS_HeaderContent.css
  FrontEnd/src/styles/BS_OnlineIdeaList.css
  FrontEnd/src/styles/BrainStormPage.css
  FrontEnd/src/styles/ChatList.css
  FrontEnd/src/styles/ChatRoomWindow.css
Labels: task

#298 Add edit delete for user and chatroom
  Backend/Database/CollectionContracts/IChatRoomCollection.cs
  Backend/Database/CollectionContracts/IUserCollection.cs
  Backend/Database/Collections/ChatRoomCollection.cs
  Backend/Database/Collections/UserCollection.cs
  Backend/Logic/Controllers/ChatRoomController.cs
  Backend/Logic/Controllers/UsersController.cs
  Backend/Logic/DTOs/ChatRoom/EditChatRoomRequest.cs
  Backend/Logic/DTOs/User/EditUserRequest.cs
  Backend/Logic/Services/AuthService.cs
  Backend/Logic/Services/ChatRoomService.cs
  FrontEnd/src/services/ApiService.ts
Labels: feature
